"""
Ollama AI Summarizer.

Connects to a local Ollama instance via HTTP to summarize the metrics payload.
Falls back gracefully if Ollama is not installed or the model is missing.

Architecture:
    SQL/Python calculates ALL metrics, rankings, and percentage-point differences.
    This module sends ONLY the precomputed 'overall' and 'key_findings' keys
    to the LLM for natural-language summarization — no raw arrays, no detailed data.
"""

import json
import requests
from typing import Dict, Any

from src.config.settings import settings
from src.config.logging_config import get_logger
from src.ai.interface import AISummarizer
from src.ai.privacy import validate_privacy
from src.ai.prompts import SYSTEM_PROMPT  # Single authoritative prompt — do not override

logger = get_logger(__name__)


class OllamaAISummarizer(AISummarizer):
    def summarize(self, metrics: Dict[str, Any]) -> str:
        # 1. Enforce privacy boundary — must pass before any external request
        validate_privacy(metrics)

        url = f"{settings.ai.ollama_base_url}/api/generate"
        model = settings.ai.ollama_model

        from src.analytics.metrics import JSONEncoder

        # 2. Build condensed payload: ONLY overall + key_findings.
        #    Do NOT send monthly_trend, detailed_data, or raw arrays.
        #    This keeps the LLM input small and prevents misinterpretation.
        condensed = {
            "overall": metrics.get("overall", {}),
            "key_findings": metrics.get("key_findings", {}),
        }

        # 3. Safe debug log — only key names, never values
        logger.debug(f"AI payload keys: {list(condensed.keys())}")

        # 4. Build the final prompt from the centralized SYSTEM_PROMPT only.
        #    No additional report format instructions are appended here.
        prompt = (
            f"{SYSTEM_PROMPT}\n\n"
            f"Here are the precomputed findings:\n"
            f"{json.dumps(condensed, cls=JSONEncoder, indent=2)}\n\n"
            f"Summarize these findings now."
        )

        payload = {
            "model": model,
            "prompt": prompt,
            "stream": False,
            "think": False,
            "options": {
                "temperature": 0.0,
                "num_predict": 300,
            },
        }

        try:
            logger.info(f"Sending metrics payload to Ollama (Model: {model}) at {url}...")
            response = requests.post(url, json=payload, timeout=600.0)
            response.raise_for_status()

            result = response.json()
            return result.get("response", "Error: No response generated by Ollama.")

        except requests.exceptions.ConnectionError:
            raise RuntimeError(f"AI backend unavailable: Could not connect to Ollama at {url}")
        except requests.exceptions.Timeout:
            raise RuntimeError("AI backend unavailable: Ollama request timed out.")
        except Exception as e:
            raise RuntimeError(f"AI backend unavailable: {str(e)}")
