"""
Ollama AI Summarizer.

Connects to a local Ollama instance via HTTP to summarize the metrics payload.
Falls back gracefully if Ollama is not installed or the model is missing.
"""

import json
import requests
from typing import Dict, Any

from src.config.settings import settings
from src.config.logging_config import get_logger
from src.ai.interface import AISummarizer
from src.ai.privacy import validate_privacy
from src.ai.prompts import SYSTEM_PROMPT

logger = get_logger(__name__)

class OllamaAISummarizer(AISummarizer):
    def summarize(self, metrics: Dict[str, Any]) -> str:
        # 1. Enforce privacy boundary
        validate_privacy(metrics)
        
        url = f"{settings.ai.ollama_base_url}/api/generate"
        model = settings.ai.ollama_model
        
        from src.analytics.metrics import JSONEncoder
        
        # Build a condensed payload with ONLY what the LLM needs to summarize.
        # This prevents the model from misinterpreting raw monthly arrays.
        condensed = {
            "overall": metrics.get("overall", {}),
            "key_findings": metrics.get("key_findings", {})
        }
        
        prompt = (
            f"{SYSTEM_PROMPT}\n\n"
            f"Here are the precomputed findings:\n"
            f"{json.dumps(condensed, cls=JSONEncoder, indent=2)}\n\n"
            f"Summarize these findings now."
        )
        
        payload = {
            "model": model,
            "prompt": prompt,
            "stream": False,
            "think": False,
            "options": {
                "temperature": 0.0,
                "num_predict": 300
            }
        }
        
        try:
            logger.info(f"Sending metrics payload to Ollama (Model: {model}) at {url}...")
            response = requests.post(url, json=payload, timeout=600.0)
            response.raise_for_status()
            
            result = response.json()
            return result.get("response", "Error: No response generated by Ollama.")
            
        except requests.exceptions.ConnectionError:
            raise RuntimeError(f"AI backend unavailable: Could not connect to Ollama at {url}")
        except requests.exceptions.Timeout:
            raise RuntimeError(f"AI backend unavailable: Ollama request timed out.")
        except Exception as e:
            raise RuntimeError(f"AI backend unavailable: {str(e)}")
