"""
Ollama AI Summarizer.

Connects to a local Ollama instance via HTTP to summarize the metrics payload.
Falls back gracefully if Ollama is not installed or the model is missing.
"""

import json
import requests
from typing import Dict, Any

from src.config.settings import settings
from src.config.logging_config import get_logger
from src.ai.interface import AISummarizer
from src.ai.privacy import validate_privacy

logger = get_logger(__name__)

SYSTEM_PROMPT = """You are an operational data analyst. You have been provided with a JSON payload of aggregated metrics for a synthetic healthcare dataset.

Your task is to write a concise operational summary of the data. 

STRICT RULES:
1. ONLY describe observed patterns in the provided data.
2. DO NOT invent statistics, metrics, or numbers not explicitly present in the data.
3. DO NOT invent causes for the data. Never claim causation from correlation. (e.g., Use "Monday has a higher observed rate" instead of "Patients miss Monday because they are busy.")
4. NEVER expose or infer personal patient information.
5. IF the data is insufficient to support a conclusion, explicitly state so.
6. YOU MUST ACKNOWLEDGE that this is a synthetic dataset.

Format your output nicely with clear sections (e.g., Overall, Key observed patterns, Operational observation, Limitations).
Keep it concise.
"""

class OllamaAISummarizer(AISummarizer):
    def summarize(self, metrics: Dict[str, Any]) -> str:
        # 1. Enforce privacy boundary
        validate_privacy(metrics)
        
        url = f"{settings.ai.ollama_host}/api/generate"
        model = settings.ai.ollama_model
        
        prompt = (
            f"{SYSTEM_PROMPT}\n\n"
            f"Here is the aggregated JSON data:\n"
            f"{json.dumps(metrics, indent=2)}\n\n"
            f"Please provide the summary now."
        )
        
        payload = {
            "model": model,
            "prompt": prompt,
            "stream": False
        }
        
        try:
            logger.info(f"Sending metrics payload to Ollama (Model: {model}) at {url}...")
            response = requests.post(url, json=payload, timeout=30.0)
            response.raise_for_status()
            
            result = response.json()
            return result.get("response", "Error: No response generated by Ollama.")
            
        except requests.exceptions.ConnectionError:
            raise RuntimeError(f"AI backend unavailable: Could not connect to Ollama at {url}")
        except requests.exceptions.Timeout:
            raise RuntimeError(f"AI backend unavailable: Ollama request timed out.")
        except Exception as e:
            raise RuntimeError(f"AI backend unavailable: {str(e)}")
